#ifndef GRAPH_CONSTANTS_H
#define GRAPH_CONSTANTS_H
const float SCREEN_WIDTH = 2500;
const float SCREEN_HEIGHT = SCREEN_WIDTH*2/3;
const float WORK_PANEL = SCREEN_WIDTH*2/3;
const float SIDE_BAR = SCREEN_WIDTH*1/3;
const float TOTAL_PTS = 750;

const float BUTTON_SIZE = SCREEN_HEIGHT/10;


const int SB_MOUSE_POSITION = 0;
const int SB_MOUSE_CLICKED = SB_MOUSE_POSITION + 1;
const int SB_KEY_PRESSED = SB_MOUSE_CLICKED + 1;
#endif // CONSTANTS_H

